#!/bin/bash
sudo systemctl enable --now pipewire
sudo systemctl enable --now pipewire-pulse
sudo systemctl enable --now wireplumber
sudo apt update
sudo apt install pipewire pipewire-pulse wireplumber
sudo pacman -Syu
sudo pacman -S pipewire pipewire-pulse wireplumber

sudo pacman -Syu
sudo pacman -Rns pulseaudio pulseaudio-bluetooth pulseaudio-equalizer pulseaudio-jack pulseaudio-lirc pulseaudio-rtp pulseaudio-zeroconf
sudo pacman -S manjaro-pipewire
